dist: trusty
language: ruby
rvm:
  - 2.5.1

addons:
  postgresql: 9.6

notifications:
  slack: pl5es:84Pa1a9D0o7hXNvlby4JeYl2

before_install:
  - cd code/server

jobs:
  include:
    - stage: Setup PostgreSQL
      script:
        - cp config/database.yml.travis config/database.yml
        - psql -c 'create database travis_ci_test;' -U postgres
    - stage: Api tests
      script:
        - bundle exec rails db:migrate RAILS_ENV=test
        - bundle exec rspec
