dist: trusty
notifications:
  slack: pl5es:84Pa1a9D0o7hXNvlby4JeYl2

stages:
  - Build Server
  - Deploy Server
  - Deploy Web

jobs:
  include:
    - stage: Build Server
      language: ruby
      rvm:
        - 2.5.1
      addons:
        postgresql: 9.6
      before_script:
        - cd code/server
        - bundle install
        - cp config/database.yml.travis config/database.yml
        - psql -c 'create database travis_ci_test;' -U postgres
      script:
        - bundle exec rubocop
        - bundle exec rails db:migrate RAILS_ENV=test
        #- bundle exec rspec

    - stage: Deploy Server
      language: generic
      before_script:
        - cd code/server
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app:
          master: pando-api-staging
        run: "rails db:migrate"

    - stage: Deploy Web
      language: generic
      before_script:
        - cd code/web
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app:
          master: pando-web-staging
